In [1]:
"""Dataset Info"""

"""
Name of dataset: Research Organization Registry Data

Dataset link: https://zenodo.org/records/7926988

Dataset download: https://zenodo.org/records/7926988/files/v1.25-2023-05-11-ror-data.zip?download=1

License: ROR is freely and openly available to anyone in public. There is no cost to access and use ROR data and services.

Size: v1.25-2023-05-11-ror-data.csv is 32.4 MB

"""

'\nName of dataset: Research Organization Registry Data\n\nDataset link: https://zenodo.org/records/7926988\n\nDataset download: https://zenodo.org/records/7926988/files/v1.25-2023-05-11-ror-data.zip?download=1\n\nLicense: ROR is freely and openly available to anyone in public. There is no cost to access and use ROR data and services.\n\nSize: v1.25-2023-05-11-ror-data.csv is 32.4 MB\n\n'

In [2]:
"""
Characteristics of this dataset:

This ROR data includes most of the well-known funders in the world, which can be used for Education, Govenment, Facility, etc. 
It contains the funder's information, such as name, links, wikipedia url, country, and so on.
Overall, there are 105294 rows for this data. 
Some of the data is string, some of them are numbers, some of them are urls. 
"""

"\nCharacteristics of this dataset:\n\nThis ROR data includes most of the well-known funders in the world, which can be used for Education, Govenment, Facility, etc. \nIt contains the funder's information, such as name, links, wikipedia url, country, and so on.\nOverall, there are 105294 rows for this data. \nSome of the data is string, some of them are numbers, some of them are urls. \n"

In [3]:
import pandas as pd
import bqplot
import json
import pandas as pd 
import bqplot.pyplot as plt
import re
import numpy as np
import random
from functools import reduce
import seaborn as sns
from ast import literal_eval
# import matplotlib.pyplot as plt
from matplotlib.colors import Normalize

In [4]:
df = pd.read_csv('v1.25-2023-05-11-ror-data.csv',encoding='iso-8859-1')
df[:100]

,id,name,types,status,links,aliases,labels,acronyms,wikipedia_url,established,...,country.country_name,external_ids.GRID.preferred,external_ids.GRID.all,external_ids.ISNI.preferred,external_ids.ISNI.all,external_ids.FundRef.preferred,external_ids.FundRef.all,external_ids.Wikidata.preferred,external_ids.Wikidata.all,relationships
0,https://ror.org/019wvm592,Australian National University,Education,active,http://www.anu.edu.au/,NaN,NaN,ANU,http://en.wikipedia.org/wiki/Australian_Nation...,1946.0,...,Australia,grid.1001.0,grid.1001.0,NaN,0000 0001 2180 7477,5.011000e+11,501100000995;501100001151;100009020,NaN,Q127990,"Related: https://ror.org/041c7s516, https://ro..."
1,https://ror.org/02bfwt286,Monash University,Education,active,http://www.monash.edu/,NaN,NaN,NaN,http://en.wikipedia.org/wiki/Monash_University,1958.0,...,Australia,grid.1002.3,grid.1002.3,NaN,0000 0004 1936 7857,5.011000e+11,501100001779;501100001144;501100007917;5011000...,NaN,Q598841,"Related: https://ror.org/0484pjq71, https://ro..."
2,https://ror.org/00rqy9422,University of Queensland,Education,active,http://www.uq.edu.au/,NaN,NaN,UQ,http://en.wikipedia.org/wiki/University_of_Que...,1909.0,...,Australia,grid.1003.2,grid.1003.2,NaN,0000 0000 9320 7537,5.011000e+11,501100001794;501100008407;501100005268,NaN,Q866012,"Related: https://ror.org/010g47133, https://ro..."
3,https://ror.org/01sf06y89,Macquarie University,Education,active,http://mq.edu.au/,NaN,NaN,NaN,http://en.wikipedia.org/wiki/Macquarie_University,1964.0,...,Australia,grid.1004.5,grid.1004.5,NaN,0000 0001 2158 5405,NaN,501100001230,NaN,Q741082,Related: https://ror.org/0402tt118; Child: htt...
4,https://ror.org/01kj2bm70,Newcastle University,Education,active,http://www.ncl.ac.uk/,University of Newcastle upon Tyne,NaN,NaN,http://en.wikipedia.org/wiki/Newcastle_University,1834.0,...,United Kingdom,grid.1006.7,grid.1006.7,NaN,0000 0001 0462 7212,NaN,501100008406;501100000774,NaN,Q837164,"Related: https://ror.org/00cdwy346, https://ro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,https://ror.org/02edavb98,Agenzia Regionale Prevenzione e Ambiente della...,Government,active,http://www.arpa.emr.it/dettaglio_generale.asp?...,NaN,en: Regional Agency for Environmental Protecti...,ARPA,NaN,1995.0,...,Italy,grid.4947.e,grid.4947.e,NaN,0000 0004 1760 8629,NaN,NaN,NaN,NaN,NaN
96,https://ror.org/05bpbnx46,Copenhagen University Hospital,Healthcare,active,https://universitetshospital.ku.dk/,NaN,da: KÃ¸benhavns Universitetshospital,KUH,https://en.wikipedia.org/wiki/Copenhagen_Unive...,1757.0,...,Denmark,grid.4973.9,grid.4973.9,NaN,0000 0004 0646 7373,NaN,501100005111,NaN,Q5168500,Related: https://ror.org/035b05819; Child: htt...
97,https://ror.org/01j5n9f07,Institute for Atomic Energy Research,Facility,active,http://www.aeki.kfki.hu/?lang=en,Atomic Energy Research Institute,hu: Atomenergia KutatÃ³intÃ©zet,AEKI; AERI,NaN,1950.0,...,Hungary,grid.4987.2,grid.4987.2,NaN,NaN,NaN,NaN,NaN,NaN,Parent: https://ror.org/05wswj918
98,https://ror.org/03613d656,Brno University of Technology,Education,active,http://www.vutbr.cz/en/,VysokÃ© UÄenÃ­ TechnickÃ© v BrnÄ,cs: VysokÃ© uÄenÃ­ technickÃ© v BrnÄ,BUT; VUT,http://en.wikipedia.org/wiki/Brno_University_o...,1899.0,...,Czechia,grid.4994.0,grid.4994.0,NaN,0000 0001 0118 0988,NaN,501100004585,NaN,Q1122171,NaN
99,https://ror.org/02jz4aj89,Maastricht University,Education,active,http://www.maastrichtuniversity.nl/,NaN,nl: Universiteit Maastricht,UM,http://en.wikipedia.org/wiki/Maastricht_Univer...,1976.0,...,Netherlands,grid.5012.6,grid.5012.6,NaN,0000 0001 0481 6099,NaN,501100001835,NaN,Q1137652,"Related: https://ror.org/01qavk531, https://ro..."

In [14]:
# Chart 1: Bar chart of the count distribution of column 'types'

fig = plt.figure(title="Count Distribution of Types")
types_counts = df['types'].value_counts()
x = list(types_counts.index)
y = types_counts.values
plt.xlabel('Types')
plt.ylabel('Count')
bar = plt.bar(x, y)
fig

Figure(axes=[Axis(scale=OrdinalScale()), Axis(orientation='vertical', scale=LinearScale())], fig_margin={'top'…

In [15]:
# Chart 2: Bar chart of the count distribution of column 'status'

fig = plt.figure(title="Count Distribution of Status")
types_counts = df['status'].value_counts()
x = list(types_counts.index)
y = types_counts.values
plt.xlabel('Status')
plt.ylabel('Count')
bar = plt.bar(x, y, colors=["salmon"])
fig

Figure(axes=[Axis(scale=OrdinalScale()), Axis(orientation='vertical', scale=LinearScale())], fig_margin={'top'…

In [22]:
# Chart 3: Bar chart of the count distribution of 'acronyms' based on has 'Acronyms' and no acronyms rows

acronyms_counts = df['acronyms'].notna().value_counts()
acronyms_chart = plt.figure(title='Count Distribution of Acronyms in Names')
x = list(acronyms_counts.index.astype(str))
y = acronyms_counts.values
acronyms_bar = plt.bar(x, y, color=["red"])
plt.xlabel('Has Acronyms')
plt.ylabel('Count')
plt.show()

VBox(children=(Figure(axes=[ColorAxis(scale=OrdinalColorScale()), Axis(label='Has Acronyms', scale=OrdinalScal…